from typing import Any

class DotDict(dict[str, Any]):
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

def deep_getattr(obj: Any, name: str, *default: Any) -> Any: ...
def deep_hasattr(obj: Any, name: str) -> bool: ...
def flexcomp(x: Any, *criteria: Any) -> bool: ...
def intersect(iterable: Any, wanteds: Any) -> Any: ...
def complement(iterable: Any, unwanteds: Any) -> Any: ...
def prodct(dct: dict[str, Any]) -> Any: ...
def transps(thing2d: Any, *args: Any, **kwargs: Any) -> Any: ...
