name: Colab compatibility

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 1 * *" # 1st of every month

jobs:
  colab:
    runs-on: ubuntu-latest
    container:
      # NOTE: a more lightweight alternative (?):
      #       https://github.com/googlecolab/backend-info/blob/main/pip-freeze.txt
      image: us-docker.pkg.dev/colab-images/public/runtime:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install DAPPER
        run: pip install -q .

      - name: Run basic_1
        env:
          MPLBACKEND: Agg
          DAPPER_LIVEPLOTTING: "0"
        run: python docs/examples/basic_1.py

      - name: Run basic_2
        env:
          MPLBACKEND: Agg
          DAPPER_LIVEPLOTTING: "0"
        run: python docs/examples/basic_2.py
